FROM node:16 as build

WORKDIR /app

COPY package.json /app
RUN npm i
COPY src /app/src
RUN npm run native

FROM alpine:3.16
ARG VERSION
ENV APP_VERSION=$VERSION

RUN apk add gcompat libstdc++

COPY --from=build /app/bin/native /

RUN chmod +x native

CMD ./native